orders_data_q1 = [
    {
        "_id": 100002,
        "orderKey": 100002,
        "orderStatus": "O",
        "totalPrice": 87642.15,
        "orderDate": {"$date": "1997-05-12T00:00:00.000Z"},
        "shipPriority": 1,
        "customer": {
            "custKey": 6789,
            "name": "Customer#000006789",
            "mktSegment": "AUTOMOBILE",
            "nationKey": 2,
            "nationName": "GERMANY",
            "regionName": "EUROPE",
        },
        "lineitems": [
            {
                "lineNumber": 1,
                "partKey": 2345,
                "suppKey": 123,
                "quantity": 15.0,
                "extendedPrice": 45620.75,
                "discount": 0.08,
                "tax": 0.03,
                "returnFlag": "A",
                "lineStatus": "F",
                "shipDate": {"$date": "1997-05-28T00:00:00.000Z"},
                "supplier_nation": {
                    "nationKey": 1,
                    "nationName": "CANADA",
                    "regionName": "AMERICA",
                },
            },
            {
                "lineNumber": 2,
                "partKey": 6789,
                "suppKey": 456,
                "quantity": 8.0,
                "extendedPrice": 42021.40,
                "discount": 0.02,
                "tax": 0.01,
                "returnFlag": "N",
                "lineStatus": "F",
                "shipDate": {"$date": "1997-05-25T00:00:00.000Z"},
                "supplier_nation": {
                    "nationKey": 3,
                    "nationName": "BRAZIL",
                    "regionName": "AMERICA",
                },
            },
        ],
    },
    {
        "_id": 100003,
        "orderKey": 100003,
        "orderStatus": "F",
        "totalPrice": 234567.89,
        "orderDate": {"$date": "1997-08-03T00:00:00.000Z"},
        "shipPriority": 0,
        "customer": {
            "custKey": 3456,
            "name": "Customer#000003456",
            "mktSegment": "BUILDING",
            "nationKey": 3,
            "nationName": "BRAZIL",
            "regionName": "AMERICA",
        },
        "lineitems": [
            {
                "lineNumber": 1,
                "partKey": 11223,
                "suppKey": 789,
                "quantity": 45.0,
                "extendedPrice": 187654.32,
                "discount": 0.10,
                "tax": 0.04,
                "returnFlag": "R",
                "lineStatus": "O",
                "shipDate": {"$date": "1997-08-20T00:00:00.000Z"},
                "supplier_nation": {
                    "nationKey": 2,
                    "nationName": "GERMANY",
                    "regionName": "EUROPE",
                },
            }
        ],
    },
    {
        "_id": 100004,
        "orderKey": 100004,
        "orderStatus": "P",
        "totalPrice": 54321.99,
        "orderDate": {"$date": "1997-11-18T00:00:00.000Z"},
        "shipPriority": 2,
        "customer": {
            "custKey": 8912,
            "name": "Customer#000008912",
            "mktSegment": "HOUSEHOLD",
            "nationKey": 1,
            "nationName": "CANADA",
            "regionName": "AMERICA",
        },
        "lineitems": [
            {
                "lineNumber": 1,
                "partKey": 4455,
                "suppKey": 334,
                "quantity": 12.5,
                "extendedPrice": 28765.50,
                "discount": 0.15,
                "tax": 0.02,
                "returnFlag": "N",
                "lineStatus": "O",
                "shipDate": {"$date": "1997-12-05T00:00:00.000Z"},
                "supplier_nation": {
                    "nationKey": 1,
                    "nationName": "CANADA",
                    "regionName": "AMERICA",
                },
            },
            {
                "lineNumber": 2,
                "partKey": 6677,
                "suppKey": 556,
                "quantity": 7.0,
                "extendedPrice": 18543.25,
                "discount": 0.05,
                "tax": 0.03,
                "returnFlag": "A",
                "lineStatus": "O",
                "shipDate": {"$date": "1997-12-10T00:00:00.000Z"},
                "supplier_nation": {
                    "nationKey": 2,
                    "nationName": "GERMANY",
                    "regionName": "EUROPE",
                },
            },
            {
                "lineNumber": 3,
                "partKey": 8899,
                "suppKey": 778,
                "quantity": 3.0,
                "extendedPrice": 7013.24,
                "discount": 0.20,
                "tax": 0.01,
                "returnFlag": "R",
                "lineStatus": "O",
                "shipDate": {"$date": "1997-12-08T00:00:00.000Z"},
                "supplier_nation": {
                    "nationKey": 3,
                    "nationName": "BRAZIL",
                    "regionName": "AMERICA",
                },
            },
        ],
    },
    {
        "_id": 100005,
        "orderKey": 100005,
        "orderStatus": "F",
        "totalPrice": 152000.00,
        "orderDate": {"$date": "1997-09-30T00:00:00.000Z"},
        "shipPriority": 0,
        "customer": {
            "custKey": 7734,
            "name": "Customer#000007734",
            "mktSegment": "MACHINERY",
            "nationKey": 2,
            "nationName": "GERMANY",
            "regionName": "EUROPE",
        },
        "lineitems": [
            {
                "lineNumber": 1,
                "partKey": 9900,
                "suppKey": 112,
                "quantity": 25.0,
                "extendedPrice": 152000.00,
                "discount": 0.12,
                "tax": 0.05,
                "returnFlag": "N",
                "lineStatus": "F",
                "shipDate": {"$date": "1997-10-15T00:00:00.000Z"},
                "supplier_nation": {
                    "nationKey": 2,
                    "nationName": "GERMANY",
                    "regionName": "EUROPE",
                },
            }
        ],
    },
]
